name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Setting up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Installing and building app
        run: |
          npm install
          npm run build
      - name: Deploying app
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
