name: React CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-deploy:
    name: Build and deploy the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build and test
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
